import Image from 'next/image';
import Link from 'next/link';

const invoiceTypes = [
  { number: '01', name: 'Tavaline müügiarve', description: 'Ühekordse toote või teenuse eest. Arvel on ostja ja müüja andmed, read, maksetähtaeg ning tasumisele kuuluv summa.' },
  { number: '02', name: 'Ettemaksuarve', description: 'Kui kokkulepe näeb ette tasumise enne töö tegemist või kauba üleandmist. Ettemaks ja lõplik arveldus vajavad selget seost.' },
  { number: '03', name: 'Korduv arve', description: 'Igakuise teenuse, rendi või hoolduse jaoks. Periood, summa ja klient lähtuvad kokkuleppest; arve vaadatakse enne väljastamist üle.' },
  { number: '04', name: 'Kreeditarve', description: 'Varasema arve paranduse või tagastuse jaoks. Seos algse arvega ja muudatuse põhjus jäävad jälgitavaks.' },
  { number: '05', name: 'E-arve', description: 'Struktureeritud arve, mida saab saata e-arve operaatori kaudu pärast päris ühenduse seadistamist.' },
  { number: '06', name: 'Väliskliendi arve', description: 'Kui ostja asub teises riigis, on oluline näidata sobiv valuuta, ettevõtte andmed ja maksukäsitlus.' },
];

export function SalesInvoicesPage() {
  return <>
    <section className="sales-hero"><div className="shell sales-hero-grid"><div><div className="eyebrow">INVO / MÜÜGIARVED</div><h1>Müügiarved, millest on lihtne aru saada.</h1><p className="sales-lead">Ühekordne teenus, regulaarne tasu või arve parandus — igal müügiarvel on oma koht. INVO müügiarvete vaade on loodud selleks, et arve sisu, olek ja laekumine oleksid ühes loogilises töövoos.</p><div className="actions"><Link className="button" href="#naidisarve">Vaata näidisarvet</Link><Link className="button sales-outline" href="/demo">Küsi demo</Link></div><p className="sales-availability">Toote eelvaade. Müügiarvete koostamine avaneb pärast kontode ja arveldusmootori valmimist.</p></div><div className="sales-hero-visual" aria-hidden="true"><div className="sales-orbit sales-orbit-one"/><div className="sales-orbit sales-orbit-two"/><div className="sales-floating-card"><span className="sales-card-top">MÜÜGIARVE <span>INV-2026-001</span></span><div className="sales-card-line"><span>Vahesumma</span><strong>150,00 €</strong></div><div className="sales-card-line"><span>Käibemaksu näide</span><strong>36,00 €</strong></div><div className="sales-card-total"><span>Kokku</span><strong>186,00 €</strong></div><span className="sales-card-stamp">NÄIDIS</span></div><div className="sales-status-pill">● Selge ülevaade</div></div></div></section>

    <section className="section sales-intro"><div className="shell sales-intro-grid"><div><div className="eyebrow">ÜKS VADE</div><h2>Arve ei ole ainult PDF.</h2></div><div><p>Müügiarve algab kokkuleppest ja lõpeb laekumisega. Vahepeal on vaja teada, kellele arve tehti, millised read sellel on, kas arve saadeti ning kas see on tasutud.</p><p>INVO kavandatud töövoog seob kliendi, arve, sündmused ja maksed. Näidisarve allpool näitab, kuidas see info võiks kliendile selgelt paista.</p></div></div></section>

    <section className="section alt sales-types"><div className="shell"><div className="section-head"><div className="eyebrow">ARVELIIGID</div><h2>Erinevad olukorrad. Ühtne arveldusloogika.</h2><p>Siin on levinud müügiarvete olukorrad, mida INVO töövoos arvestame. Täpne maksukäsitlus sõltub tehingust ja ettevõtte seadistusest.</p></div><div className="sales-type-grid">{invoiceTypes.map(type => <article className="sales-type-card" key={type.number}><span>{type.number}</span><h3>{type.name}</h3><p>{type.description}</p></article>)}</div></div></section>

    <section className="section sales-flow"><div className="shell"><div className="section-head"><div className="eyebrow">TÖÖVOOG</div><h2>Koostamisest laekumiseni.</h2><p>Arve elukaare iga samm peaks olema arusaadav nii selle koostajale kui ka kliendile.</p></div><ol className="sales-flow-list"><li><span>1</span><div><h3>Vali klient</h3><p>Lisa ostja andmed ja vajadusel kontaktisik.</p></div></li><li><span>2</span><div><h3>Koosta read</h3><p>Määra teenus või toode, kogus, ühikuhind, maksukäsitlus ja tähtaeg.</p></div></li><li><span>3</span><div><h3>Kontrolli ja väljasta</h3><p>Vaata arve enne saatmist üle. PDF on kavandatud; e-arve saatmine vajab operaatori ühendust.</p></div></li><li><span>4</span><div><h3>Jälgi laekumist</h3><p>Arve olek ja maksete ajalugu aitavad näha, mis on tasutud ning mis ootab veel laekumist.</p></div></li></ol></div></section>

    <section className="section alt sales-example" id="naidisarve"><div className="shell"><div className="sales-example-head"><div><div className="eyebrow">NÄIDISARVE</div><h2>Selline võiks müügiarve välja näha.</h2><p>Allolev arve on kujundusnäidis väljamõeldud andmetega. See ei ole väljastatud arve ega maksenõue.</p></div><span className="sales-preview-label">NÄIDIS · MITTE TASUMISEKS</span></div><div className="invoice-paper" aria-label="INVO näidismüügiarve"><div className="invoice-top"><div><div className="invoice-logo-crop"><Image src="/invo-logo.png" alt="INVO logo" width={123} height={73} priority /></div><p className="invoice-seller"><strong>Näidisettevõte OÜ</strong><br/>Näidistänav 1, Tallinn<br/>kontakt@naidis.ee</p></div><div className="invoice-identity"><span className="invoice-word">MÜÜGIARVE</span><strong>INV-2026-001</strong><span>NÄIDIS · MITTE TASUMISEKS</span></div></div><div className="invoice-meta"><div><small>ARVE SAAJA</small><strong>Näidisklient OÜ</strong><span>Klienditänav 2, Tartu</span></div><div><small>ARVE KUUPÄEV</small><strong>21.09.2026</strong><span>Maksetähtaeg 05.10.2026</span></div><div><small>VIITENUMBER</small><strong>1001</strong><span>Valuuta EUR</span></div></div><div className="invoice-table-wrap"><table className="invoice-table"><thead><tr><th>Kirjeldus</th><th>Kogus</th><th>Ühiku hind</th><th>Summa</th></tr></thead><tbody><tr><td>Veebidisaini teenus</td><td>1</td><td>125,00 €</td><td>125,00 €</td></tr><tr><td>Majutusteenus</td><td>1</td><td>25,00 €</td><td>25,00 €</td></tr></tbody></table></div><div className="invoice-bottom"><p>Arve sisu ja maksukäsitlus on näitlikud. Päris arvel lähtutakse ettevõtte andmetest ning tehingu tingimustest.</p><div className="invoice-totals"><div><span>Vahesumma</span><strong>150,00 €</strong></div><div><span>Käibemaksu näide (24%)</span><strong>36,00 €</strong></div><div className="invoice-grand-total"><span>Tasuda kokku</span><strong>186,00 €</strong></div></div></div></div></div></section>

    <section className="section sales-faq"><div className="shell sales-faq-grid"><div><div className="eyebrow">KÜSIMUSED</div><h2>Oluline enne arve saatmist.</h2></div><div className="faq"><details><summary>Kas see näidisarve on allalaaditav või saadetav?</summary><p>Ei. See on avaliku lehe kujundusnäidis. Päris arve koostamine, PDF ja saatmine lisanduvad koos turvalise kontosüsteemiga.</p></details><details><summary>Kas INVO saadab e-arveid?</summary><p>E-arve saatmiseks on vaja seadistatud operaatori ühendust. Avaldame funktsiooni alles siis, kui see töötab päriselt.</p></details><details><summary>Kas käibemaksumäär on alati 24%?</summary><p>Ei. Näidisarve kasutab lihtsalt üht arvutusnäidet. Tegelik maksukäsitlus sõltub tehingust ja ettevõtte seadistusest.</p></details></div></div></section>

    <section className="section"><div className="shell"><div className="cta-box"><div><div className="eyebrow">RÄÄGIME LÄHEMALT</div><h2>Millist arveldusvoogu sinu ettevõte vajab?</h2><p>Kirjelda oma vajadust ja anname teada, kuidas INVO arendus sellega haakub.</p></div><Link className="button cream" href="/kontakt">Saada päring</Link></div></div></section>
  </>;
}

