import Link from 'next/link';
import { nav, pricing } from '@/lib/content';

export function Logo(){return <Link href="/" className="logo" aria-label="INVO avaleht">IN<span>V</span>O<span>.</span></Link>}
export function Header(){return <header className="header"><div className="shell topbar"><Logo/><nav className="nav" aria-label="Peamenüü">{nav.map(x=><Link key={x.href} href={x.href}>{x.label}</Link>)}<Link href="/login">Logi sisse</Link><Link href="/register" className="button">Alusta tasuta</Link></nav><details className="mobile-nav"><summary>Menüü</summary>{nav.map(x=><Link key={x.href} href={x.href}>{x.label}</Link>)}<Link href="/login">Logi sisse</Link><Link href="/register">Alusta tasuta</Link></details></div></header>}
export function Footer(){return <footer className="footer"><div className="shell"><div className="footer-grid"><div><Logo/><p style={{marginTop:22}}>Arved. Maksed. Automatiseerimine. Ühes kohas.</p><a href="mailto:tere@invo.ee">tere@invo.ee</a></div><div><h3>Toode</h3><Link href="/lahendused">Lahendused</Link><Link href="/e-arved">E-arved</Link><Link href="/hinnad">Hinnad</Link><Link href="/integratsioonid">Integratsioonid</Link></div><div><h3>Avasta</h3><Link href="/arendajatele">Arendajatele</Link><Link href="/ressursid">Ressursid</Link><Link href="/abi">Abi</Link><Link href="/kontakt">Kontakt</Link></div><div><h3>Ettevõte</h3><Link href="/meist">Meist</Link><Link href="/turvalisus">Turvalisus</Link><Link href="/privaatsus">Privaatsus</Link><Link href="/kasutustingimused">Tingimused</Link><Link href="/cookies">Küpsised</Link></div></div><div className="footer-bottom">© {new Date().getFullYear()} INVO · Arveldamine ilma käsitööta.</div></div></footer>}
export function Pricing(){return <div className="price-grid">{pricing.map(p=><article className={'price '+(p.name==='BUSINESS'?'featured':'')} key={p.name}><div className="eyebrow">{p.name}</div><strong>{p.price}</strong><small>{p.name==='ENTERPRISE'?'': 'kuus · '} {p.detail}</small><ul className="list">{p.features.map(f=><li key={f}>{f}</li>)}</ul><Link href={p.name==='ENTERPRISE'?'/kontakt':'/register'} className="button" style={{marginTop:28,width:'100%'}}>{p.name==='ENTERPRISE'?'Võta ühendust':'Alusta tasuta'}</Link></article>)}</div>}
export function Dashboard(){return <div className="dashboard" role="img" aria-label="INVO töölaua illustratsioon: arved, tulud ja e-arve olek"><div className="dash-head"><span className="dash-logo">INVO / Ülevaade</span><span>September 2026</span></div><div className="dash-stats"><div className="stat"><small>Kuu tulu</small><strong>24 860 €</strong></div><div className="stat"><small>Laekumata</small><strong>8 420 €</strong></div><div className="stat"><small>Aktiivsed arved</small><strong>18</strong></div></div><div className="chart">{[35,52,43,65,58,78,69,94,73,88].map((x,i)=><div key={i} className="bar" style={{height:x+'%'}}/>)}</div><div className="invoice-list"><small>Viimased arved</small><div className="dash-row"><span>INV-2026-104 · Nord Partner OÜ</span><span className="badge">Tasutud</span></div><div className="dash-row"><span>INV-2026-103 · Kask Kinnisvara</span><span className="badge pending">Ootel</span></div><div className="dash-row"><span>E-arve ühendus</span><span className="badge pending">Seadistamata</span></div></div></div>}

