export type Page = { title: string; eyebrow: string; description: string; points: string[]; cta?: string };
export const pricing = [
  { name: 'START', price: '0 €', detail: 'Alustavale ettevõttele', features: ['1 kasutaja', 'PDF-arved', 'Kliendibaas'] },
  { name: 'BUSINESS', price: '12 €', detail: 'Kasvavale meeskonnale', features: ['Korduvate arvete töövoog', 'Meeldetuletuste töövoog', 'Arhiiv ja aruanded', 'Integratsioonid seadistamise järel'] },
  { name: 'PRO', price: '29 €', detail: 'Keerukamatele protsessidele', features: ['Kuni 5 kasutajat', 'Kinnitusringid', 'API ja veebikonksud', 'Prioriteetne tugi'] },
  { name: 'ENTERPRISE', price: 'Kokkuleppel', detail: 'Eritellimusega vajadustele', features: ['Kohandatud kasutajate arv', 'Läbimõeldud juurutus', 'Eraldi kokkulepped'] },
];
export const pages: Record<string, Page> = {
  'lahendused': { eyebrow: 'Lahendused', title: 'Arveldamine ühes töövoos.', description: 'INVO toob arved, kliendid ja korduvad tegevused ühte selgesse vaatesse.', points: ['Müügi- ja ostuarved', 'Lepingupõhine arveldamine', 'Kinnitused ja ülevaated'] },
  'lahendused/muegiarved': { eyebrow: 'Müügiarved', title: 'Arve koostamisest laekumiseni.', description: 'Koosta selged müügiarved ja jälgi nende olekut ühest kohast.', points: ['Arve read ja käibemaks', 'PDF ja arve ajalugu', 'Laekumiste jälgimine'] },
  'lahendused/ostuarved': { eyebrow: 'Ostuarved', title: 'Ostuarved kontrolli alla.', description: 'Kogu tarnijate arved ja kinnitused ühte töövoogu.', points: ['Tarnijate ülevaade', 'Kinnitamise töövoog', 'Dokumentide arhiiv'] },
  'lahendused/e-arved': { eyebrow: 'E-arved', title: 'E-arved ilma segaduseta.', description: 'Valmistu struktureeritud arvelduseks. Saatmine vajab päris teenusepakkuja ühendust.', points: ['Valideerimise alus', 'Operaatori ühendamise koht', 'Selge tarneolek'] },
  'lahendused/korduv-arveldus': { eyebrow: 'Automatiseerimine', title: 'Korduvad arved õigel ajal.', description: 'Kavanda püsivaid arveldusperioode ja vähenda käsitööd.', points: ['Kuu, kvartal või aasta', 'Lepinguga seotud arved', 'Kontrollitav ajalugu'] },
  'lahendused/arvete-kinnitamine': { eyebrow: 'Kinnitamine', title: 'Selge otsus enne tasumist.', description: 'Loo ostuarvetele läbipaistev kinnitamise kord.', points: ['Vastutajad', 'Olekud', 'Otsuste ajalugu'] },
  'lahendused/kuluaruanded': { eyebrow: 'Kulud', title: 'Kulud nähtavaks.', description: 'Hoia kuludokumente ja aruandeid ühes loogilises kohas.', points: ['Dokumendid', 'Kulude liigitamine', 'Ülevaated'] },
  'lahendused/arhiiv': { eyebrow: 'Arhiiv', title: 'Dokumendid leitavad.', description: 'Leia arved ja seotud failid ilma kaustades ekslemata.', points: ['Otsing', 'Ajalugu', 'Seotud kirjed'] },
  'lahendused/korteriuhistud': { eyebrow: 'Korteriühistud', title: 'Korduvad arved igale ühistule.', description: 'Struktureeri liikmete, kulude ja perioodiliste arvete töö.', points: ['Perioodiline arveldamine', 'Üksused', 'Kulude jaotus'] },
  'lahendused/kinnisvarahaldus': { eyebrow: 'Kinnisvarahaldus', title: 'Lepingust arveni.', description: 'Planeeri üüri, hoolduse ja kommunaalkulude arveldust.', points: ['Objektid ja üksused', 'Lepingud', 'Korduvad tasud'] },
  'lahendused/raamatupidajatele': { eyebrow: 'Raamatupidajatele', title: 'Ülevaade mitmest ettevõttest.', description: 'Korralda klientide arveldus ja üleandmine selges keskkonnas.', points: ['Mitme organisatsiooni vaade', 'Aruanded', 'Ekspordi võimalused'] },
  'e-arved': { eyebrow: 'E-arved', title: 'Struktureeritud arvelduse suunas.', description: 'E-arve saatmine sõltub seadistatud operaatorist. INVO ei väida end olevat Peppoli juurdepääsupunkt.', points: ['Operaatori vajadus on nähtav', 'Tarneolekud', 'Andmete kontroll'] },
  'peppol': { eyebrow: 'Peppol', title: 'Valmis võrguga liitumiseks.', description: 'Peppoli ühendus vajab sertifitseeritud teenusepakkujat ja aktiivset seadistust.', points: ['Avatud arhitektuur', 'Vormingu kontroll', 'Aus ühenduse olek'] },
  'automatiseerimine': { eyebrow: 'Automatiseerimine', title: 'Vähem korduvaid samme.', description: 'Kujunda reeglid arvetele, meeldetuletustele ja kinnitustele.', points: ['Korduvad arved', 'Töövood', 'Jälgitavad sündmused'] },
  'integratsioonid': { eyebrow: 'Integratsioonid', title: 'Ühenda vajalikud tööriistad.', description: 'Integratsioonid vajavad päris ühendust. Avaldame saadavuse alles pärast seadistamist.', points: ['Raamatupidamistarkvara: tulekul', 'Pangaliidesed: tulekul', 'E-arve operaator: vajab seadistust'] },
  'arendajatele': { eyebrow: 'Arendajatele', title: 'Ehita oma töövoo ümber.', description: 'Versioonitud API ja veebikonksud on kavandatud järgmistes etappides.', points: ['Selged ressursid', 'Turvalised võtmed', 'Sündmuspõhine töövoog'] },
  'arendajatele/api': { eyebrow: 'API', title: 'API arvelduse jaoks.', description: 'API avalik dokumentatsioon lisandub pärast toimiva ja turvatud liidese valmimist.', points: ['Versioonitud rajad', 'Organisatsiooni õigused', 'Piirangud ja audit'] },
  'arendajatele/webhooks': { eyebrow: 'Veebikonksud', title: 'Sündmused õigesse kohta.', description: 'Allkirjastatud veebikonksud on plaanis pärast API taristu valmimist.', points: ['Arvete sündmused', 'Korduskatsed', 'Tarneajalugu'] },
  'ressursid': { eyebrow: 'Ressursid', title: 'Teadmised arveldamiseks.', description: 'Leia juhendid, abi ja värsked tooteuudised.', points: ['Juhendid', 'Abikeskus', 'Blogi'] },
  'blogi': { eyebrow: 'Blogi', title: 'Mõtted selgemast arveldamisest.', description: 'Esimesed artiklid ilmuvad siin. Vaata seni juhendeid ja abikeskust.', points: ['Arvelduse põhitõed', 'Automatiseerimine', 'Tooteuudised'] },
  'blogi/mis-on-e-arve': { eyebrow: 'Blogi · E-arved', title: 'Mis on e-arve?', description: 'E-arve on struktureeritud andmetega dokument, mida süsteemid saavad automaatselt töödelda. PDF üksi ei ole e-arve.', points: ['Masinloetavad andmed', 'Vormingu kontroll', 'Saatmine vajab operaatorit'] },
  'blogi/korduv-arveldus': { eyebrow: 'Blogi · Automatiseerimine', title: 'Millal tasub korduvat arveldust kasutada?', description: 'Püsiva teenuse või rendi puhul aitab kindel arveldusperiood hoida tähtajad ja tasud ühes rütmis.', points: ['Määra periood', 'Kontrolli tasu', 'Jälgi laekumist'] },
  'juhendid': { eyebrow: 'Juhendid', title: 'Alusta kindla sammuga.', description: 'Siin selgitame arve, e-arve ja makse töövoogu. Detailsemad õpetused lisanduvad koos tootega.', points: ['Koosta arve', 'Jälgi laekumist', 'Valmista ette e-arve'] },
  'abi': { eyebrow: 'Abi', title: 'Kuidas saame aidata?', description: 'Leia vastused konto, müügiarvete, ostuarvete, e-arvete, maksete, integratsioonide ja API teemal.', points: ['Konto ja ligipääs', 'Arved ja maksed', 'Integratsioonid ja API'] },
  'abi/konto': { eyebrow: 'Abi · Konto', title: 'Konto ja ligipääs', description: 'Kontosüsteem pole veel avatud. Pärast käivitamist saab kasutaja kuuluda mitmesse ettevõttesse ning õigused määratakse rolli järgi.', points: ['Registreerimine avaneb pärast turvakontrolli', 'Parooli taastamine lisandub koos kontodega', 'Abi: tere@invo.ee'] },
  'abi/arved-ja-maksed': { eyebrow: 'Abi · Arved', title: 'Arved ja maksed', description: 'Müügi- ja ostuarvete töövood ning maksete kirjendamine valmivad pärast konto- ja andmekihi loomist.', points: ['Arve summad arvutatakse serveris', 'Osalised maksed on plaanis', 'E-arved vajavad operaatori ühendust'] },
  'abi/integratsioonid-ja-api': { eyebrow: 'Abi · Integratsioonid', title: 'Integratsioonid ja API', description: 'API, veebikonksud ja välised ühendused ei ole praegu aktiivsed. Töö käib turvalise võtme- ja õigustemudeli suunas.', points: ['API versioonimine', 'Allkirjastatud sündmused', 'Ühenduse oleku läbipaistvus'] },
  'kontakt': { eyebrow: 'Kontakt', title: 'Räägime sinu arveldusest.', description: 'Kirjuta aadressile tere@invo.ee. Vastame esimesel võimalusel.', points: ['Toote küsimused', 'Koostöö', 'Tagasiside'], cta: 'Kirjuta meile' },
  'demo': { eyebrow: 'Demo', title: 'Tutvu INVO suunaga.', description: 'Demo broneerimine pole veel avatud. Kirjuta meile ja võtame sinuga ühendust.', points: ['Töövoo ülevaade', 'Sinu vajadused', 'Järgmised sammud'], cta: 'Küsi demo' },
  'meist': { eyebrow: 'Meist', title: 'Rohkem aega päris tööks.', description: 'INVO eesmärk on muuta ettevõtte arveldamine selgeks ja usaldusväärseks.', points: ['Eestist lähtuv', 'Läbipaistev', 'Praktiline'] },
  'turvalisus': { eyebrow: 'Turvalisus', title: 'Usaldus algab läbipaistvusest.', description: 'Toote turvakontrollid ja teenusetaseme kirjeldus avaldatakse enne kontode avamist.', points: ['Rollipõhine ligipääs kavandamisel', 'Auditijälg kavandamisel', 'Turvalised ühendused'] },
  'privaatsus': { eyebrow: 'Õigusteave', title: 'Privaatsus', description: 'See on esialgne teave, mis vajab juristi ülevaatust enne teenuse avamist. Praegune avalik sait ei kogu kontode ega arvete andmeid.', points: ['Kontakt: tere@invo.ee', 'Andmekaitse tingimused täpsustatakse enne registreerimise avamist', 'Ärikriitilised andmed vajavad eraldi töötlemistingimusi'] },
  'kasutustingimused': { eyebrow: 'Õigusteave', title: 'Kasutustingimused', description: 'Esialgne kirjeldus vajab juristi ülevaatust. Teenuse kasutajakontosid ja tasulisi tellimusi praegu ei avata.', points: ['Teenuse ulatus täpsustatakse', 'Arveldustingimused avaldatakse enne müüki', 'Küsimused: tere@invo.ee'] },
  'cookies': { eyebrow: 'Õigusteave', title: 'Küpsised', description: 'Sait ei kasuta praegu analüütika ega reklaami küpsiseid. Teave vaadatakse üle enne uute teenuste lisamist.', points: ['Vajalikud tehnilised küpsised võivad olla seotud majutusega', 'Analüütika pole seadistatud', 'Kontakt: tere@invo.ee'] },
  'login': { eyebrow: 'Konto', title: 'Sisselogimine avaneb peagi.', description: 'Turvaline konto ja organisatsioonide süsteem valmib järgmises etapis.', points: ['Turvalised sessioonid', 'Mitme ettevõtte tugi', 'Rollipõhine ligipääs'] },
  'register': { eyebrow: 'Konto', title: 'Liitu ootenimekirjaga.', description: 'Registreerimine avaneb pärast autentimise ja andmekihi valmimist. Huvi korral kirjuta meile.', points: ['Konto loomine tulekul', 'Ettevõtte seadistamine tulekul', 'Arvelduse töölaud tulekul'], cta: 'Anna huvist teada' },
  'forgot-password': { eyebrow: 'Konto', title: 'Parooli taastamine tuleb koos kontodega.', description: 'Kontosüsteem pole veel avatud. Küsimuse korral kirjuta meile.', points: ['Turvaline taastamine on kavandatud', 'Kontosid praegu ei looda'] },
};
export const nav = [
  { label: 'Lahendused', href: '/lahendused' }, { label: 'E-arved', href: '/e-arved' }, { label: 'Integratsioonid', href: '/integratsioonid' }, { label: 'Hinnad', href: '/hinnad' }, { label: 'Ressursid', href: '/ressursid' }
];
export const allPaths = [...Object.keys(pages), 'hinnad'];

