import Link from 'next/link';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { allPaths, pages } from '@/lib/content';
import { Pricing } from '@/components/site';
import { ContactForm } from '@/components/contact-form';
import { SalesInvoicesPage } from '@/components/sales-invoices-page';
export function generateStaticParams(){return allPaths.map(x=>({slug:x.split('/')}))}
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}):Promise<Metadata>{const {slug}=await params; const key=slug.join('/'); const p=pages[key]; return {title:p?.title ?? (key==='hinnad'?'Hinnad':'INVO'),description:p?.description ?? 'INVO hinnad'}}
export default async function ContentPage({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;const key=slug.join('/');if(key==='lahendused/muegiarved')return <SalesInvoicesPage/>;if(key==='hinnad')return <><section className="page-hero"><div className="shell"><div className="eyebrow">Hinnad</div><h1>Õige plaan igaks etapiks.</h1><p className="lead">Selged kavandatud kuuhinnad. Aastapõhine arveldus lisandub teenuse avamisel. Kontosid praegu ei avata.</p></div></section><section className="section"><div className="shell"><Pricing/><p className="muted" style={{marginTop:24}}>E-arveldus eeldab teenusepakkuja seadistust. Funktsioonide saadavus täpsustub enne tellimuste avamist.</p></div></section></>;const p=pages[key];if(!p)notFound();if(key==='demo'||key==='kontakt')return <><section className="page-hero"><div className="shell"><div className="eyebrow">{p.eyebrow}</div><h1>{key==='demo'?'Leiame sobiva demoaja.':'Räägime sinu arveldusest.'}</h1><p className="lead">{key==='demo'?'Kirjelda, mida soovid näha. Vastame e-posti teel ja lepime aja kokku.':'Saada küsimus või kirjelda oma vajadust. Vastame e-posti teel.'}</p></div></section><section className="section"><div className="shell form-shell"><ContactForm kind={key==='demo'?'demo':'inquiry'}/></div></section></>;return <><section className="page-hero"><div className="shell"><div className="eyebrow">{p.eyebrow}</div><h1>{p.title}</h1><p className="lead">{p.description}</p><div className="actions"><Link className="button" href="/kontakt">Räägime lähemalt</Link><Link className="button secondary" href="/lahendused">Vaata lahendusi</Link></div></div></section><section className="section"><div className="shell split"><div><div className="eyebrow">INVO</div><h2>Selgem töövoog, vähem käsitööd.</h2><p className="copy">{p.description}</p></div><div className="card"><h3>Olulised teemad</h3><ul className="list">{p.points.map(x=><li key={x}>{x}</li>)}</ul></div></div></section>{['blogi','abi','ressursid'].includes(key)&&<section className="section"><div className="shell"><h2>Sirvi sisu</h2><div className="link-grid">{(key==='blogi'?['blogi/mis-on-e-arve','blogi/korduv-arveldus']:['abi/konto','abi/arved-ja-maksed','abi/integratsioonid-ja-api']).map(x=><Link key={x} className="link-card" href={'/'+x}>{pages[x].title} →</Link>)}</div></div></section>}<section className="section alt"><div className="shell"><div className="section-head"><div className="eyebrow">Avasta edasi</div><h2>Leia oma järgmine samm.</h2></div><div className="link-grid"><Link className="link-card" href="/lahendused">Kõik lahendused →</Link><Link className="link-card" href="/hinnad">Hinnad →</Link><Link className="link-card" href="/kontakt">Kontakt →</Link></div></div></section></>}

